version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - llama
    networks:
      - app-network
 
  llama:
    image: llama3.2:latest
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge
 